import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { formatDualTime, formatHorizon, formatModelVersion, formatPercent, formatPrice, formatRatio, formatRebalance, formatSide, formatStrategyMode, formatUniverseName, humanizeToken } from "../lib/formatters";
export function TradePlanTable({ rows }) {
    return (_jsx("div", { className: "table-shell", children: _jsxs("table", { className: "data-table trade-plan-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: "Side" }), _jsx("th", { children: "Status" }), _jsx("th", { children: "Horizon" }), _jsx("th", { children: "Symbol" }), _jsx("th", { children: "Entry" }), _jsx("th", { children: "SL" }), _jsx("th", { children: "TP" }), _jsx("th", { children: "RR" }), _jsx("th", { children: "Expected" }), _jsx("th", { children: "Confidence" }), _jsx("th", { children: "Expiry" }), _jsx("th", { children: "Universe" }), _jsx("th", { children: "Strategy" }), _jsx("th", { children: "Model" })] }) }), _jsx("tbody", { children: rows.map((row) => {
                        const expiry = formatDualTime(row.expiresAt);
                        const model = formatModelVersion(row.modelVersion);
                        return (_jsxs("tr", { children: [_jsx("td", { children: _jsx("span", { className: `side-pill side-pill--${row.side}`, children: formatSide(row.side) }) }), _jsx("td", { children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { className: row.actionable ? "status-pill status-pill--actionable" : "status-pill status-pill--filtered", children: row.actionable ? "Actionable" : "Filtered" }), _jsx("span", { children: row.rejectionReason ?? "Meets entry / SL / TP / RR filter" })] }) }), _jsx("td", { children: formatHorizon(row.horizon) }), _jsx("td", { children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { children: row.symbol }), _jsx("span", { children: row.executionSymbol && row.executionSymbol !== row.symbol ? `Exec ${row.executionSymbol}` : humanizeToken(row.executionMode) })] }) }), _jsx("td", { children: formatPrice(row.entryPrice) }), _jsx("td", { children: formatPrice(row.stopLossPrice) }), _jsx("td", { children: formatPrice(row.takeProfitPrice) }), _jsx("td", { children: formatRatio(row.riskRewardRatio) }), _jsx("td", { children: formatPercent(row.expectedReturn, 2) }), _jsx("td", { children: formatPercent(row.confidence, 0) }), _jsx("td", { title: expiry.title, children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { children: expiry.primary }), _jsx("span", { children: expiry.secondary ?? row.expiresAt })] }) }), _jsx("td", { title: row.universe, children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { children: formatUniverseName(row.universe) }), _jsx("span", { children: row.market.replace("_", " ") })] }) }), _jsx("td", { children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { children: formatStrategyMode(row.strategyMode) }), _jsx("span", { children: formatRebalance(row.rebalanceFreq) })] }) }), _jsx("td", { title: model.title, children: _jsxs("div", { className: "table-cell-stack", children: [_jsx("strong", { children: model.primary }), _jsx("span", { children: model.secondary ?? row.modelVersion })] }) })] }, `${row.symbol}-${row.universe}-${row.strategyMode}-${row.rebalanceFreq}-${row.horizon}-${row.side}`));
                    }) })] }) }));
}
