import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Panel } from "@newquantmodel/ui";
import { ForecastDistribution } from "../components/ForecastDistribution";
import { MetricCard } from "../components/MetricCard";
import { PriceTapeChart } from "../components/PriceTapeChart";
import { ChipList, ValueBlock } from "../components/ValueBlock";
import { formatCompactPath, formatCoverageMode, formatDualTime, formatMarketName, formatModelVersion, formatPercent, formatUniverseName } from "../lib/formatters";
export function OverviewPage({ generatedAt, universes, dataHealth, forecasts, reportPath, modelVersions }) {
    const averageCoverage = dataHealth.length > 0 ? `${(dataHealth.reduce((sum, item) => sum + item.coveragePct, 0) / dataHealth.length).toFixed(1)}%` : "Pending";
    const tradableCoverage = dataHealth.length > 0 ? `${(dataHealth.reduce((sum, item) => sum + item.tradableCoveragePct, 0) / dataHealth.length).toFixed(1)}%` : "Pending";
    const topSignals = [...forecasts].sort((left, right) => right.expectedReturn - left.expectedReturn).slice(0, 6);
    const staleMarkets = dataHealth.filter((item) => item.stale).length;
    const publishedTime = formatDualTime(generatedAt);
    const reportPathDisplay = formatCompactPath(reportPath);
    const modelChips = modelVersions.map((item) => {
        const version = formatModelVersion(item);
        return { label: version.primary, title: version.secondary ?? item };
    });
    return (_jsxs("div", { className: "page-grid", children: [_jsx(Panel, { title: "Platform State", eyebrow: "Overview", children: _jsxs("div", { className: "metric-grid metric-grid--overview", children: [_jsx(MetricCard, { label: "Published Snapshot", value: publishedTime.primary, secondary: publishedTime.secondary, title: publishedTime.title, wide: true }), _jsx(MetricCard, { label: "Universes", value: String(universes.length) }), _jsx(MetricCard, { label: "Forecast Rows", value: String(forecasts.length) }), _jsx(MetricCard, { label: "Coverage Mode", value: "Batch Published", hint: "TS online, Python offline" }), _jsx(MetricCard, { label: "Average Coverage", value: averageCoverage }), _jsx(MetricCard, { label: "Tradable Coverage", value: tradableCoverage }), _jsx(MetricCard, { label: "Stale Markets", value: String(staleMarkets) }), _jsxs("article", { className: "metric-card metric-card--wide", children: [_jsx("span", { className: "metric-card__label", children: "Model Stack" }), _jsx(ChipList, { items: modelChips.length > 0 ? modelChips : [{ label: "Baseline Signals" }] }), _jsx("span", { className: "metric-card__hint", children: "Latest published versions" })] })] }) }), _jsx(Panel, { title: "Market Coverage", eyebrow: "Freshness + PIT status", children: _jsx("div", { className: "value-grid value-grid--status", children: dataHealth.map((item) => (_jsx(ValueBlock, { label: formatMarketName(item.market), primary: `${formatPercent(item.coveragePct / 100, 1)} coverage`, secondary: `${formatPercent(item.tradableCoveragePct / 100, 1)} tradable / ${formatCoverageMode(item.membershipMode)}`, tertiary: `History from ${item.historyStartDate} / stale: ${String(item.stale)}` }, `${item.market}-${item.lastRefreshAt}`))) }) }), _jsx(Panel, { title: "Top Signals", eyebrow: "Latest publish", children: _jsx("div", { className: "jobs-list", children: topSignals.map((item) => (_jsxs("article", { className: "job-row", children: [_jsxs("strong", { children: [item.symbol, " / ", formatUniverseName(item.universe)] }), _jsxs("span", { children: [item.horizon, " / ", formatModelVersion(item.modelVersion).primary] }), _jsxs("span", { children: [formatPercent(item.expectedReturn, 2), " expected / ", (item.confidence * 100).toFixed(0), "% confidence"] }), _jsx("span", { children: item.regime })] }, `${item.symbol}-${item.universe}-${item.horizon}`))) }) }), _jsx(Panel, { title: "Return Distribution", eyebrow: "Cross-market", children: _jsx(ForecastDistribution, { items: forecasts }) }), _jsx(Panel, { title: "Price Tape", eyebrow: "Median trajectory", children: _jsx(PriceTapeChart, { items: forecasts }) }), _jsx(Panel, { title: "Research Report", eyebrow: "Latest export", children: _jsx(ValueBlock, { label: "PDF report", primary: reportPathDisplay.primary, secondary: reportPathDisplay.secondary ?? "No report published yet", title: reportPathDisplay.title, className: "value-block--report" }) })] }));
}
